---
#Drush 7 for Drupal 7, drush 8 for backdrop.  Drush 9 is installed as a site-local version only.
- name: Clone drush from Github
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: "/usr/local/src/drush{{ item[0:1] }}"
    version: "{{ item }}"
  register: drush_clone
  with_items: "{{ drushversion }}"
  tags: [drush,drupal]

- name: Set Ansible, not root as file owner so Composer doesn't complain
  file:
    path: "/usr/local/src/drush{{ item[0:1] }}"
    recurse: yes
    owner: "{{ ansible_user }}"
  with_items: "{{ drushversion }}"
  tags: [drush,drupal]

- name: Install Drush dependencies with composer
  composer:
    command: install
    prefer_source: yes
    working_dir: "/usr/local/src/drush{{ item[0:1] }}"
  with_items: "{{ drushversion  }}"
  tags: [drush,drupal]
  become_user: "{{ ansible_user }}"

- name: Link drush executable
  file:
    src: "/usr/local/src/drush{{ item[0:1] }}/drush"
    dest: "/usr/local/bin/drush{{ item[0:1] }}"
    state: link
  with_items: "{{ drushversion  }}"
  tags: [drush,drupal]

- name: install drush-launcher
  get_url:
    url: https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
    dest: /usr/local/bin/drush-launcher
    mode: u=rwx,g=rx,o=rx

- name: copy drush Script
  copy: src=files/drush dest=/usr/local/bin/drush mode=0755
  tags: [drush,backdrop]
